language: java
jdk:
 - oraclejdk8
notifications:
  slack: 
    secure: ld8g+N5gXHtKgcnR/GhKWuUpiA/zQ5jLT2LFZdGjoT3XQxa60Jpz58rI8ScAAvepcMjJxmvMlTjcVzPYBSUwMnKkLv3qYfWiWNOKLD4egaP/eU4MybMWK3eRvti5cbeJuEOeBNh2wmgKnb+KN+CSPL62y0/QiQJxYP4v5IemuxYFS96m6tM2QYlnUlovJ0d6O7fgunJeInbRMRtVHilpvSObhtG4nJXs3U7fzsaOi/1OJkvcMNfPozzVwFwXPSlW60IXqCPx+cB72bP/K57mSrZLtEGTsgugG8+iKLuJdZjMOEJI7bPVyLg/6WTXN95WM1kyDfTTkUTx/Wg6zS3qUAnkV4nSOQczVfzzl1bCAENR3UPQLa36W8UBZrzfSGkm7iWXn38hEJs3pLxaAOAz/liYRBrQ8cOfk2cBsoKst96zi2s35553u8vWV6pLZRaIvr4hCGQEeqI/g6yjr9DRQEbj0Lw4yBSgbNNwrOnm/smO8YwkNXI21xAl4LS/+hVPXUb+YQJKM8O6472TN7CHflTSOhQXh+FqiDS3wk4c7fAD02sPX7K7bV4Tk5wK5OMhK8uycdn8Yw3NyJbL1Q4sYhIxzgNF9h5puSCRCPQhqPU+Boj0n0GWDjbJGU3kZZ/plvuj2rAQ1rN0jLC54NwJd4N4ZmFB+O3EpmzkVU3hcNI=

